FROM python:3.12-slim-bookworm AS runtime

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

COPY master/requirements.txt /app/master/requirements.txt
RUN pip install --no-cache-dir -r /app/master/requirements.txt

COPY master/ /app/master/

WORKDIR /app/master

EXPOSE 8000

CMD ["python", "-m", "src.server"]
